ROS2Mower_area_recording:
  ros__parameters:
    joy_toggle_polygon: 3 # toggle polygon recording on/off
    joy_keepout: 0 # button to store last polygon as keepout zone
    joy_area: 2 # button to store last polygon as outer polygon of area
    joy_clear: 11 # clear last recorded poly
    joy_clear_all: 12 # clear entire recorded map
    joy_save: 1 # save map
    publish_polygon: true # visualize polygon
    distance_points: 0.2 # distance between points while recording
    base_frame: 'base_footprint'  # base frame of robot
    map_frame: 'map' # map frame of robot

